I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 6, in script
    $ game_loop()
  File "game/script.rpy", line 6, in <module>
    $ game_loop()
  File "game/script.rpy", line 27, in game_loop
    game2(colors)
  File "game/script.rpy", line 240, in game2
    secret_code = dragged_secret_code(row, secret_code, draggable, droppable)
UnboundLocalError: local variable 'row' referenced before assignment

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 6, in script
    $ game_loop()
  File "C:\Apps\renpy-8.3.3.24091901+nightly-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Apps\renpy-8.3.3.24091901+nightly-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 6, in <module>
    $ game_loop()
  File "game/script.rpy", line 27, in game_loop
    game2(colors)
  File "game/script.rpy", line 240, in game2
    secret_code = dragged_secret_code(row, secret_code, draggable, droppable)
UnboundLocalError: local variable 'row' referenced before assignment

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.3.24091901+nightly
Mastermind 1.0
Fri Nov 22 16:15:23 2024
